[project]
name = "warg-shell"
version = "1.2.0"
description = "DigitalOcean Warg - SSH-like connection to DigitalOcean PaaS console"
readme = "README.md"
license = "WTFPL"
authors = [
    { name = "Rémy Sanchez", email = "remy.sanchez@hyperthese.net" },
]
requires-python = ">=3.11"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: System :: Shells",
]
dependencies = [
    "click",
    "httpx",
    "keyring",
    "psutil",
    "rich",
    "rich-click",
    "websockets",
]

[project.urls]
Homepage = "https://github.com/Starkstonks/warg-shell"
Issues = "https://github.com/Starkstonks/warg-shell/issues"

[project.scripts]
warg-shell = "warg_shell._cli:main"

[project.entry-points."keyring.backends"]
warg_shell_wsl = "warg_shell._keyring"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-timeout>=2.4.0",
    "ruff",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/warg_shell"]

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = [
    # -- Core --
    "E",  # pycodestyle (errors)
    "W",  # pycodestyle (warnings)
    "F",  # Pyflakes
    "I",  # isort
    "C90",  # McCabe Complexity
    "D1",  # Mandatory docstrings
    "S",  # Bandit

    # -- Bonus --
    "A",  # flake8-bugbear
    "B",  # flake8-bugbear
    "DTZ",  # date/time zone
    "T10",  # debugger
    "EM",  # error messages
    "EXE",  # executable
    "G",  # logging
    "UP",  # pyupgrade
    "ASYNC",  # async
    "INP",  # PEP 420
    "T20",  # no print
    "PT",  # pytest
    "SLOT",  # slots
    "TCH",  # type checking blocks
    "PTH",  # Use pathlib
    "FIX",  # Don't allow not done stuff in code
    "ERA",  # Don't comment code
    "RUF",  # Ruff stuff
    "TID251",  # See below
]

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"requests".msg = "Use `httpx` instead, which has timeouts by default."

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
timeout = 30
timeout_method = "thread"

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["ARG001", "S101", "S105"]
"tests/conftest.py" = ["S105"]
